global:
  logging_params:
    log_dir: "logs"
    name: "paper_c_rnn_jvae_search"

  schedules_path: "tmp/nts_home_schedules.csv"
  attributes_path: "tmp/nts_home_attributes_groups.csv"

  conditionals:
    gender: nominal
    age: nominal
    # ethnicity: nominal
    # education: nominal
    # license: nominal
    car_access: nominal
    work_status: nominal
    # area: nominal
    income: nominal
    # hh_size: ordinal
    # hh_composition: nominal
    # hh_children: ordinal
    # hh_cars: ordinal
    # hh_bikes: ordinal
    # hh_motorcycles: ordinal

  # evaluation_params:
  #   split_on: [gender, age, car_access, work_status, income]

  attribute_encoder: "tokens"

  encoder_params:
    name: "sequence"
    max_length: 12
    norm_duration: 1440
    jitter: 0.2

  model_params:
    name: "JVAESeqLSTM"
    hidden_layers: 4
    hidden_size: 128
    latent_dim: 24
    dropout: 0.1
    teacher_forcing_ratio: 0.5

  loader_params:
    train_batch_size: 1024
    val_batch_size:  1024
    num_workers: 8

  trainer_params:
    min_epochs: 30
    patience: 30
    max_epochs: 100

  # experiment_params:
  #   LR: 0.01
  #   weight_decay: 0.0
  #   scheduler_gamma: 0.95
  #   kld_weight: 0.0001
  #   label_loss_weight: 0.00001

ll_000001:
  seed: 11111
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_weight: 0.0001
    label_loss_weight: 0.000001

ll_000005:
  seed: 22222
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_weight: 0.0001
    label_loss_weight: 0.000005

ll_00001:
  seed: 33333
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_weight: 0.0001
    label_loss_weight: 0.00001

ll_00005:
  seed: 44444
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_weight: 0.0001
    label_loss_weight: 0.00005

ll_0001:
  seed: 55555
  experiment_params:
    LR: 0.01
    weight_decay: 0.0
    scheduler_gamma: 0.95
    kld_weight: 0.0001
    label_loss_weight: 0.0001
